### ISSUE TITLE
FPM for 5.3.20 and 5.3.23

### ISSUE THREAD

**Issue by SocalNick** [mattheath/puppet-php#20]
Filing this as a placeholder for us to hack on it tomorrow.

I tried changing my project to use 5.3.20. When I ran boxen, it compiled PHP 5.3.20 successfully, however, towards the end of the boxen script I got:

Error: Execution of '/bin/launchctl start dev.php-fpm.5.3.20' returned 1: launchctl start error: Bad file descriptor

Error: /Stage[main]/Php::Fpm::5_3_20/Php::Fpm[5.3.20]/Php::Fpm::Service[5.3.20]/Service[dev.php-fpm.5.3.20]/ensure: change from stopped to running failed: Execution of '/bin/launchctl start dev.php-fpm.5.3.20' returned 1: launchctl start error: Bad file descriptor

Error: /Stage[main]/Php::Fpm::5_3_20/Php::Fpm[5.3.20]/Php::Fpm::Service[5.3.20]/Service[dev.php-fpm.5.3.20]: Failed to call refresh: Execution of '/bin/launchctl start dev.php-fpm.5.3.20' returned 1: launchctl start error: Bad file descriptor

Error: /Stage[main]/Php::Fpm::5_3_20/Php::Fpm[5.3.20]/Php::Fpm::Service[5.3.20]/Service[dev.php-fpm.5.3.20]: Execution of '/bin/launchctl start dev.php-fpm.5.3.20' returned 1: launchctl start error: Bad file descriptor

**Comment by webflo** [comment]
Here is fix for this issue. https://github.com/dicrew/puppet-php/commit/f43bd15cf4e5b3b91bb6b8a211e4641b92684593

**Comment by mattheath** [comment]
Thanks @webflo will push this up today

**Comment by mattheath** [comment]
Fixed in `0.5.1`, @SocalNick could you confirm this?

**Comment by mattheath** [comment]
Pretty certain this is fixed, closing.
