### ISSUE TITLE
Set MySQL default socket to BOXEN_MYSQL_SOCKET

### ISSUE THREAD

**Issue by nomasprime** [mattheath/puppet-php#41]
Looked through some code but can't see how this is specified.

**Comment by mattheath** [comment]
It's in the `php.ini` file which each php version is given a copy of. It's not set, so it should fall back to the PHP default:

_pdo_mysql_: https://github.com/mattheath/puppet-php/blob/master/templates/php.ini.erb#L1013
_mysql_: https://github.com/mattheath/puppet-php/blob/master/templates/php.ini.erb#L1167
_mysqli_: https://github.com/mattheath/puppet-php/blob/master/templates/php.ini.erb#L1226

As noted in #32 its currently not easy to customise this unfortunately

**Comment by nomasprime** [comment]
@mattheath unless I'm missing something, couldn't we just inject BOXEN_MYSQL_SOCKET?

**Comment by mattheath** [comment]
Yeah, fair point. This should probably be changed.

**Comment by mattheath** [comment]
Fixed in boxen/puppet-php#10
