### ISSUE TITLE
No Clue

### ISSUE THREAD

**Issue by outrunthewolf** [mattheath/puppet-php#53]
I'm trying to use your boxen repo, I literally have no clue how it translates into my current setup. Any chance you can help or point me in the right direction. 

Could be helpful for others, here is my project manifest:

```
class projects::api {
    boxen::project { 'api':
        server_name => 'dev.api.local.com',
        source      => 'local/api',
        nginx       => true,
        redis       => true,
    }
}
```

How would I integrate PHP into this scenario?

**Comment by ivorisoutdoors** [comment]
@outrunthewolf Bottom section of the README

```
# your-boxen/modules/projects/manifests/trollin.pp

class projects::trollin {

  php::project { 'trollin':
    source        => 'boxen/trollin',
    elasticsearch => true,
    mysql         => true,
    nginx         => 'php/nginx/nginx.conf.erb',
    redis         => true,
    php           => '5.3.23',
  }
}
```

**Comment by mattheath** [comment]
@outrunthewolf as @mloberg mentioned this should be covered at the bottom of the README - you can either copy this section of the manifest, or use it as an example to create your own puppet manifest.
