### ISSUE TITLE
First time builds failing

### ISSUE THREAD

**Issue by boztek** [mattheath/puppet-php#8]
Clean machine + default boxen type project.
Latest puppet-php

``` puppet
class { 'php::global':
  version => '5.3.21',
}
```

This fails with:

```
Error: Cannot create /opt/boxen/phpenv/versions/5.3.20/modules; parent directory /opt/boxen/phpenv/versions/5.3.20 does not exist
Error: /Stage[main]/Php::5-3-20/Php::Version[5.3.20]/File[/opt/boxen/phpenv/versions/5.3.20/modules]/ensure: change from absent to directory failed: Cannot create /opt/boxen/phpenv/versions/5.3.20/modules; parent directory /opt/boxen/phpenv/versions/5.3.20 does not exist
```

Retrying with a difference version number then succeeds.

This is a pattern - some times it will complete first time with no errors but /versions will be empty but again switching to a different version (any version) works on the second attempt.

Strange one.

**Comment by mattheath** [comment]
Apologies for this, the `module` folder definition within each version didn't have a reliance on the php version being installed first. It's fixed in f8bbb4fd8fae728423aff464ee5ce6987a3c1ec5, and the latest version `0.3.5`. @boztek could you let me know it that fixes it?

**Comment by boztek** [comment]
I think so but now I'm getting different errors related to PEAR.

``` puppet
Error: /Stage[main]/Php::5-3-18/Php::Version[5.3.18]/Exec[pear-5.3.18-cache_dir]: Could not evaluate: Could not find command '/opt/boxen/phpenv/versions/5.3.18/bin/pear'
Error: /Stage[main]/Php::5-3-18/Php::Version[5.3.18]/Exec[pear-5.3.18-download_dir]: Could not evaluate: Could not find command '/opt/boxen/phpenv/versions/5.3.18/bin/pear'
.
.
.
Warning: /Stage[main]/Php::Global/File[/opt/boxen/phpenv/version]: Skipping because of failed dependencies
```

I opened a new issue at #11.

**Comment by boztek** [comment]
I think we can close this issue now.
